// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mokeb.Infrastructure.Context;

#nullable disable

namespace Mokeb.Infrastructure.Migrations
{
    [DbContext(typeof(MokebDbContext))]
    partial class MokebDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.CaravanPrincipal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CaravanPrincipals", (string)null);
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.Companion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalId");

                    b.ToTable("Companions", (string)null);
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.FAQ", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.ToTable("FAQs", (string)null);
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.Gallery", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Galleries", (string)null);
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.IndividualPrincipal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("IndividualPrincipals", (string)null);
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.PublicCommunication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("PublicCommunications", (string)null);
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.Request", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CaravanPrincipalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfAcceptingRequest")
                        .HasColumnType("datetime2");

                    b.Property<long>("FemaleCount")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("IndividualPrincipalId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("MaleCount")
                        .HasColumnType("bigint");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeOfEntrance")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeOfExit")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CaravanPrincipalId");

                    b.HasIndex("IndividualPrincipalId");

                    b.ToTable("Requests", (string)null);
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Capacity")
                        .HasColumnType("bigint");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Rooms", (string)null);
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.RoomAvailability", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("AvailableCapacity")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("AvailableDay")
                        .HasColumnType("date");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.ToTable("RoomAvailability");
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.Travelers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FamilyName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NationalNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RequestId");

                    b.ToTable("Travelers", (string)null);
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.CaravanPrincipal", b =>
                {
                    b.OwnsOne("Mokeb.Domain.Model.ValueObjects.ContactInformation", "ContactInformation", b1 =>
                        {
                            b1.Property<Guid>("CaravanPrincipalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("EmergencyPhoneNumber")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)");

                            b1.Property<string>("Gmail")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)");

                            b1.HasKey("CaravanPrincipalId");

                            b1.ToTable("CaravanPrincipals");

                            b1.WithOwner()
                                .HasForeignKey("CaravanPrincipalId");
                        });

                    b.OwnsOne("Mokeb.Domain.Model.ValueObjects.IdentityInformation", "IdentityInformation", b1 =>
                        {
                            b1.Property<Guid>("CaravanPrincipalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BloodType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("CaravanPrincipalId");

                            b1.ToTable("CaravanPrincipals");

                            b1.WithOwner()
                                .HasForeignKey("CaravanPrincipalId");
                        });

                    b.OwnsMany("Mokeb.Domain.Model.Entities.Pilgrim", "Pilgrims", b1 =>
                        {
                            b1.Property<Guid>("CaravanPrincipalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<DateOnly>("DateOfBirth")
                                .HasColumnType("date");

                            b1.Property<string>("FamilyName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<int>("Gender")
                                .HasColumnType("int");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("NationalNumber")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.Property<string>("PassportNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)");

                            b1.HasKey("CaravanPrincipalId", "Id");

                            b1.ToTable("Pilgrims", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CaravanPrincipalId");
                        });

                    b.Navigation("ContactInformation")
                        .IsRequired();

                    b.Navigation("IdentityInformation")
                        .IsRequired();

                    b.Navigation("Pilgrims");
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.Companion", b =>
                {
                    b.HasOne("Mokeb.Domain.Model.Entities.IndividualPrincipal", null)
                        .WithMany("Companion")
                        .HasForeignKey("PrincipalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.IndividualPrincipal", b =>
                {
                    b.OwnsOne("Mokeb.Domain.Model.ValueObjects.ContactInformation", "ContactInformation", b1 =>
                        {
                            b1.Property<Guid>("IndividualPrincipalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("EmergencyPhoneNumber")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)");

                            b1.Property<string>("Gmail")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)");

                            b1.HasKey("IndividualPrincipalId");

                            b1.ToTable("IndividualPrincipals");

                            b1.WithOwner()
                                .HasForeignKey("IndividualPrincipalId");
                        });

                    b.OwnsOne("Mokeb.Domain.Model.ValueObjects.IdentityInformation", "IdentityInformation", b1 =>
                        {
                            b1.Property<Guid>("IndividualPrincipalId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("BloodType")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Password")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<int>("Role")
                                .HasColumnType("int");

                            b1.Property<string>("Username")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("IndividualPrincipalId");

                            b1.ToTable("IndividualPrincipals");

                            b1.WithOwner()
                                .HasForeignKey("IndividualPrincipalId");
                        });

                    b.Navigation("ContactInformation")
                        .IsRequired();

                    b.Navigation("IdentityInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.PublicCommunication", b =>
                {
                    b.OwnsOne("Mokeb.Domain.Model.ValueObjects.Address", "IranAddress", b1 =>
                        {
                            b1.Property<Guid>("PublicCommunicationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Alley")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Iran_Alley");

                            b1.Property<string>("Area")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Iran_Area");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Iran_City");

                            b1.Property<long>("Floor")
                                .HasColumnType("bigint")
                                .HasColumnName("Iran_Floor");

                            b1.Property<long>("LicensePlate")
                                .HasColumnType("bigint")
                                .HasColumnName("Iran_LicensePlate");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Iran_PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Iran_Street");

                            b1.Property<long>("Unit")
                                .HasColumnType("bigint")
                                .HasColumnName("Iran_Unit");

                            b1.HasKey("PublicCommunicationId");

                            b1.ToTable("PublicCommunications");

                            b1.WithOwner()
                                .HasForeignKey("PublicCommunicationId");
                        });

                    b.OwnsOne("Mokeb.Domain.Model.ValueObjects.Address", "MokebAddress", b1 =>
                        {
                            b1.Property<Guid>("PublicCommunicationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Alley")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Mokeb_Alley");

                            b1.Property<string>("Area")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Mokeb_Area");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Mokeb_City");

                            b1.Property<long>("Floor")
                                .HasColumnType("bigint")
                                .HasColumnName("Mokeb_Floor");

                            b1.Property<long>("LicensePlate")
                                .HasColumnType("bigint")
                                .HasColumnName("Mokeb_LicensePlate");

                            b1.Property<string>("PostalCode")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)")
                                .HasColumnName("Mokeb_PostalCode");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasMaxLength(150)
                                .HasColumnType("nvarchar(150)")
                                .HasColumnName("Mokeb_Street");

                            b1.Property<long>("Unit")
                                .HasColumnType("bigint")
                                .HasColumnName("Mokeb_Unit");

                            b1.HasKey("PublicCommunicationId");

                            b1.ToTable("PublicCommunications");

                            b1.WithOwner()
                                .HasForeignKey("PublicCommunicationId");
                        });

                    b.Navigation("IranAddress")
                        .IsRequired();

                    b.Navigation("MokebAddress")
                        .IsRequired();
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.Request", b =>
                {
                    b.HasOne("Mokeb.Domain.Model.Entities.CaravanPrincipal", null)
                        .WithMany("Requests")
                        .HasForeignKey("CaravanPrincipalId");

                    b.HasOne("Mokeb.Domain.Model.Entities.IndividualPrincipal", null)
                        .WithMany("Requests")
                        .HasForeignKey("IndividualPrincipalId");

                    b.OwnsMany("Mokeb.Domain.Model.ValueObjects.RequestRoom", "Rooms", b1 =>
                        {
                            b1.Property<Guid>("RequestId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<long>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("bigint");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<long>("Id"));

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("RequestId", "Id");

                            b1.ToTable("RequestRoom");

                            b1.WithOwner()
                                .HasForeignKey("RequestId");
                        });

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.RoomAvailability", b =>
                {
                    b.HasOne("Mokeb.Domain.Model.Entities.Room", null)
                        .WithMany("RoomAvailabilities")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.Travelers", b =>
                {
                    b.HasOne("Mokeb.Domain.Model.Entities.Request", null)
                        .WithMany("Travelers")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.CaravanPrincipal", b =>
                {
                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.IndividualPrincipal", b =>
                {
                    b.Navigation("Companion");

                    b.Navigation("Requests");
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.Request", b =>
                {
                    b.Navigation("Travelers");
                });

            modelBuilder.Entity("Mokeb.Domain.Model.Entities.Room", b =>
                {
                    b.Navigation("RoomAvailabilities");
                });
#pragma warning restore 612, 618
        }
    }
}
